server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SarozDev/EA_Final_Project
          username: SarozDev
          password: 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
          default-label: "main"
  security:
    user:
      name: root
      password: password