version: '3.8'

services:

  springboot-app:
    image: sourav40/review-service:latest
    restart: always
    build: .
    ports:
      - 8000-8999:8080
    depends_on:
      - mysqldb
    environment:
      APP_PROFILE: prod
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_DATABASE_NAME: review-service
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root@12345
    networks:
      - spring-batch-mysql

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /Users/sourav.shrestha/mysql/data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: review-service
      MYSQL_ROOT_PASSWORD: root@12345
    networks:
      - spring-batch-mysql

networks:
  spring-batch-mysql: