server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: TvSeriesService
        uri: http://localhost:8080/
        predicates:
        - Path=/tv-series/**

management:
  endpoints:
    web:
      exposure:
        include: "*"