package edu.miu.dtos;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

@Data
@ApiModel(description = "Request model for series Comment add") //swagger documentation
public class SeriesCommentRequestDto {

    @ApiModelProperty(notes = "This field is autogenerated")
    private Long id;

    @NotEmpty(message = "title cannot be null or empty")
    private String title;

    @NotEmpty(message = "description cannot be null or empty")
    private String description;

    @NotNull(message = "movieId cannot be null")
    private Long seriesId;

    @NotNull(message = "userId cannot be null")
    private Long userId;
}
