server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true
#  zipkin:
#    base-url: http://localhost:9411/
#    discovery-client-enabled: true
#    enabled: true
#  sleuth.sampler.probability: 1.0
  application:
    name: movie-service
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


keycloak:
  realm: eaimdb-realm
  auth-server-url: http://localhost:8080
  resource: eaimdb-client
  public-client: true
  bearer-only: true


#resilience4j:
#  circuitbreaker:
#    instances:
#      movie-service:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        waitDurationInOpenState: 5s
#        slidingWindowType: COUNT_BASED

management:
#  health:
#    circuitbreakers:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always



