#spring.datasource.url = jdbc:postgresql://localhost:5432/comment-db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comment-db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: postgres
    password: Admin@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9090

keycloak:
  realm: comment-realm
  auth-server-url: http://localhost:8080
  resource: comment-keycloak
  public-client: true
  bearer-only: true


